### PR TITLE
Add Hamiltonian equations to qchem and qspin

### PR DESCRIPTION
**Pull request by DSGuala**
## Shortcut ticket

https://app.shortcut.com/xanaduai/story/48779/spin-systems-show-hamiltonian-equations-like-the-molecules

### CODE REVIEW

**Comment by DSGuala** [comment]
[SC-48779]

**Comment by DSGuala** [comment]
[SC-48779]

**Comment by DSGuala** [comment]
[sc-48779]

**Review by anthayes92 — APPROVED** [review]
LGTM! Would also be good to check in `dev` if possible, thanks @DSGuala!

**Pull request merged**
